[package]
name = "theremin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.7.4"
pest_derive = "2.7.4"
egg = "0.9.5"
substring = "1.4.5"
itertools = "0.11.0"
regex = "1.10.2"
